package view.viewKaryawan;

import view.viewKaryawan.KaryawanForm;
import table.TableFormKaryawan.TableStokObat;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import control.ObatControl;
import java.util.HashSet;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import model.Obat;
/**
 *
 * @author Alfonsus Setiawan Jacub
 */
public class CRUDObatForm extends javax.swing.JFrame {
    //Field : Atribut
    private ObatControl obatControl;
    String action = null;
    List<Obat> listobat;
    int selectedID = 0;
    int stat = 0;// status mouse untuk pencarian
    
    //Konstruktor
    public CRUDObatForm() {    
        initComponents();
        setComponent(false);
        setEditDeleteBtn(false);
        obatControl = new ObatControl();
        showObat();
    }
    
    //Method-method
    public void setComponent(boolean value)
    {
        inputKode.setEnabled(value);
        inputNama.setEnabled(value);
        inputKhasiat.setEnabled(value);
        inputSediaan.setEnabled(value);
        inputModal.setEnabled(value);
        inputStok.setEnabled(value);
        
        btnSimpan.setEnabled(value);
        btnBatal.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value)
    {
        btnUbah.setEnabled(value);
        btnHapus.setEnabled(value);
    }
    
    public void clearText()
    {
        inputKode.setText("");
        inputNama.setText("");
        inputKhasiat.setText("");
        inputSediaan.setText("");
        inputModal.setText("");
        inputStok.setText("");
        
        inputSearch.setText("");
    }
    
    public void showObat()
    {
        tableStokObat.setModel(obatControl.showObat(""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane3 = new javax.swing.JScrollPane();
        ContainerPanel = new javax.swing.JPanel();
        AppBarPanel = new javax.swing.JPanel();
        AppBarLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableStokObat = new javax.swing.JTable();
        labelDataObat = new javax.swing.JLabel();
        labelKodeObat = new javax.swing.JLabel();
        labelInputData = new javax.swing.JLabel();
        labelNamaObat = new javax.swing.JLabel();
        labelSediaanObat = new javax.swing.JLabel();
        labelKhasiat = new javax.swing.JLabel();
        labelModal = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();
        inputSearch = new javax.swing.JTextField();
        inputKode = new javax.swing.JTextField();
        inputNama = new javax.swing.JTextField();
        inputSediaan = new javax.swing.JTextField();
        inputKhasiat = new javax.swing.JTextField();
        inputModal = new javax.swing.JTextField();
        inputStok = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ContainerPanel.setBackground(new java.awt.Color(255, 255, 255));

        AppBarPanel.setBackground(new java.awt.Color(0, 0, 153));

        AppBarLabel.setForeground(new java.awt.Color(255, 255, 255));
        AppBarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AppBarLabel.setText("SMART APOTEK");

        javax.swing.GroupLayout AppBarPanelLayout = new javax.swing.GroupLayout(AppBarPanel);
        AppBarPanel.setLayout(AppBarPanelLayout);
        AppBarPanelLayout.setHorizontalGroup(
            AppBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AppBarPanelLayout.setVerticalGroup(
            AppBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AppBarLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jScrollPane2.setColumnHeaderView(null);
        jScrollPane2.setViewportView(null);

        tableStokObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "null"
            }
        ));
        tableStokObat.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableStokObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableStokObatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableStokObat);
        if (tableStokObat.getColumnModel().getColumnCount() > 0) {
            tableStokObat.getColumnModel().getColumn(0).setMinWidth(50);
            tableStokObat.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableStokObat.getColumnModel().getColumn(1).setResizable(false);
            tableStokObat.getColumnModel().getColumn(1).setPreferredWidth(300);
            tableStokObat.getColumnModel().getColumn(2).setResizable(false);
            tableStokObat.getColumnModel().getColumn(2).setPreferredWidth(200);
            tableStokObat.getColumnModel().getColumn(3).setPreferredWidth(500);
            tableStokObat.getColumnModel().getColumn(4).setPreferredWidth(200);
            tableStokObat.getColumnModel().getColumn(5).setPreferredWidth(200);
            tableStokObat.getColumnModel().getColumn(6).setPreferredWidth(200);
        }

        labelDataObat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDataObat.setForeground(new java.awt.Color(0, 0, 0));
        labelDataObat.setText("DATA OBAT");

        labelKodeObat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelKodeObat.setForeground(new java.awt.Color(0, 0, 0));
        labelKodeObat.setText("Kode Obat : ");

        labelInputData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInputData.setForeground(new java.awt.Color(0, 0, 0));
        labelInputData.setText("INPUT DATA ");

        labelNamaObat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNamaObat.setForeground(new java.awt.Color(0, 0, 0));
        labelNamaObat.setText("Nama Obat :");

        labelSediaanObat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSediaanObat.setForeground(new java.awt.Color(0, 0, 0));
        labelSediaanObat.setText("Sediaan Obat :");

        labelKhasiat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelKhasiat.setForeground(new java.awt.Color(0, 0, 0));
        labelKhasiat.setText("Khasiat :");

        labelModal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelModal.setForeground(new java.awt.Color(0, 0, 0));
        labelModal.setText("Modal :");

        labelStok.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelStok.setForeground(new java.awt.Color(0, 0, 0));
        labelStok.setText("Stok");

        inputSearch.setBackground(new java.awt.Color(204, 204, 255));
        inputSearch.setForeground(new java.awt.Color(0, 0, 0));
        inputSearch.setText("Cari Disini");
        inputSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputSearchMouseEntered(evt);
            }
        });
        inputSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSearchActionPerformed(evt);
            }
        });

        inputKode.setBackground(new java.awt.Color(204, 204, 255));
        inputKode.setForeground(new java.awt.Color(0, 0, 0));
        inputKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKodeActionPerformed(evt);
            }
        });

        inputNama.setBackground(new java.awt.Color(204, 204, 255));
        inputNama.setForeground(new java.awt.Color(0, 0, 0));
        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        inputSediaan.setBackground(new java.awt.Color(204, 204, 255));
        inputSediaan.setForeground(new java.awt.Color(0, 0, 0));
        inputSediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSediaanActionPerformed(evt);
            }
        });

        inputKhasiat.setBackground(new java.awt.Color(204, 204, 255));
        inputKhasiat.setForeground(new java.awt.Color(0, 0, 0));
        inputKhasiat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKhasiatActionPerformed(evt);
            }
        });

        inputModal.setBackground(new java.awt.Color(204, 204, 255));
        inputModal.setForeground(new java.awt.Color(0, 0, 0));
        inputModal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputModalActionPerformed(evt);
            }
        });

        inputStok.setBackground(new java.awt.Color(204, 204, 255));
        inputStok.setForeground(new java.awt.Color(0, 0, 0));
        inputStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputStokActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(255, 255, 0));
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(0, 0, 204));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(255, 255, 255));
        btnBatal.setForeground(new java.awt.Color(0, 0, 204));
        btnBatal.setText("batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 255, 255));
        btnUbah.setForeground(new java.awt.Color(255, 0, 51));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(255, 255, 153));
        btnTambah.setForeground(new java.awt.Color(0, 0, 0));
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(255, 255, 255));
        btnKembali.setForeground(new java.awt.Color(0, 0, 204));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContainerPanelLayout = new javax.swing.GroupLayout(ContainerPanel);
        ContainerPanel.setLayout(ContainerPanelLayout);
        ContainerPanelLayout.setHorizontalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AppBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ContainerPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(ContainerPanelLayout.createSequentialGroup()
                                    .addComponent(labelSediaanObat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputSediaan, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ContainerPanelLayout.createSequentialGroup()
                                    .addComponent(labelKhasiat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputKhasiat, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ContainerPanelLayout.createSequentialGroup()
                                    .addComponent(labelModal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputModal, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ContainerPanelLayout.createSequentialGroup()
                                    .addComponent(labelStok, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ContainerPanelLayout.createSequentialGroup()
                                    .addComponent(labelKodeObat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputKode, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ContainerPanelLayout.createSequentialGroup()
                                    .addComponent(labelNamaObat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ContainerPanelLayout.createSequentialGroup()
                                    .addComponent(labelInputData, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnTambah)))
                            .addGroup(ContainerPanelLayout.createSequentialGroup()
                                .addComponent(labelDataObat, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContainerPanelLayout.createSequentialGroup()
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addGap(38, 38, 38)
                                .addComponent(btnBatal)
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan))
                            .addGroup(ContainerPanelLayout.createSequentialGroup()
                                .addComponent(btnKembali)
                                .addGap(141, 141, 141)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        ContainerPanelLayout.setVerticalGroup(
            ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContainerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AppBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataObat)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInputData, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKodeObat)
                    .addComponent(inputKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaObat)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSediaanObat)
                    .addComponent(inputSediaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKhasiat)
                    .addComponent(inputKhasiat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModal)
                    .addComponent(inputModal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStok)
                    .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ContainerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKembali)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(ContainerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        KaryawanForm dv = new KaryawanForm();
        this.dispose();
        dv.setVisible(true);
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        setComponent(true);
        inputSearch.setText("");
        action = "Tambah";
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah yakin ingin menghapus data ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        switch (getAnswer) {
            case 0:
            try {
                  obatControl.deleteObat(String.valueOf(inputKode.getText()));
                clearText();
                showObat();
                setComponent(false);
                setEditDeleteBtn(false);
            } catch (Exception e) {
                System.out.println("Error : " + e.getMessage());
            }
            break;

            case 1:
            break;
            default:
            throw new AssertionError();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        setComponent(true);
        inputKode.setEnabled(false);
        action = "Ubah";
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        setComponent(false);
        clearText();
        showObat();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try{
            if(action.equals("Tambah"))
            {
                Obat o = new Obat(inputKode.getText(), inputNama.getText(), inputSediaan.getText(),inputKhasiat.getText(),Float.parseFloat(inputModal.getText()),Integer.parseInt(inputStok.getText()) );
                obatControl.insertObat(o);
            }else
            {
                 Obat o = new Obat(inputKode.getText(), inputNama.getText(), inputSediaan.getText(),inputKhasiat.getText(),Float.parseFloat(inputModal.getText()),Integer.parseInt(inputStok.getText()) );
                 obatControl.updateObat(o,inputKode.getText());
            }
            clearText();
            showObat();
            setComponent(false);
            setEditDeleteBtn(false);
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        setEditDeleteBtn(false);
        setComponent(false);
        btnBatal.setEnabled(true);
        
        try{
           TableStokObat tblObat = obatControl.showObat(inputSearch.getText()); 
           if(tblObat.getRowCount() == 0){
                clearText();
                setEditDeleteBtn(false);
                JOptionPane.showConfirmDialog(null, "Data tidak ditemukan", "Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
               System.out.println(tblObat.getRowCount());
                tableStokObat.setModel(tblObat);
            }
            clearText();
        }catch(Exception e){
         System.out.println("Error : "+e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void inputStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputStokActionPerformed

    private void inputModalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputModalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputModalActionPerformed

    private void inputKhasiatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKhasiatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKhasiatActionPerformed

    private void inputSediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSediaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSediaanActionPerformed

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void inputKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKodeActionPerformed

    private void inputSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSearchActionPerformed

    private void inputSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSearchMouseEntered
       if(stat==0)
       {
        inputSearch.setText("");
        stat=1;
       }
    }//GEN-LAST:event_inputSearchMouseEntered

    private void tableStokObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableStokObatMouseClicked
        setEditDeleteBtn(true);
        setComponent(false);
        
        int clickedRow = tableStokObat.getSelectedRow();
        TableModel tableModel = tableStokObat.getModel();
        
        inputKode.setText(tableModel.getValueAt(clickedRow, 0).toString());
        inputNama.setText(tableModel.getValueAt(clickedRow, 1).toString());
        inputSediaan.setText(tableModel.getValueAt(clickedRow, 2).toString());
        inputKhasiat.setText(tableModel.getValueAt(clickedRow, 3).toString());
        inputModal.setText(tableModel.getValueAt(clickedRow, 5).toString());
        inputStok.setText(tableModel.getValueAt(clickedRow, 6).toString());
        
    }//GEN-LAST:event_tableStokObatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDObatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUDObatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppBarLabel;
    private javax.swing.JPanel AppBarPanel;
    private javax.swing.JPanel ContainerPanel;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField inputKhasiat;
    private javax.swing.JTextField inputKode;
    private javax.swing.JTextField inputModal;
    private javax.swing.JTextField inputNama;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JTextField inputSediaan;
    private javax.swing.JTextField inputStok;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelDataObat;
    private javax.swing.JLabel labelInputData;
    private javax.swing.JLabel labelKhasiat;
    private javax.swing.JLabel labelKodeObat;
    private javax.swing.JLabel labelModal;
    private javax.swing.JLabel labelNamaObat;
    private javax.swing.JLabel labelSediaanObat;
    private javax.swing.JLabel labelStok;
    private javax.swing.JTable tableStokObat;
    // End of variables declaration//GEN-END:variables
}
